#!/bin/bash

echo "🚀 Vercel Postgres Setup Helper"
echo "================================"
echo ""
echo "Since I can't directly access your Vercel account, please follow these steps:"
echo ""
echo "1. Open your browser and go to:"
echo "   👉 https://vercel.com/bttr/bttr-ai/stores"
echo ""
echo "2. Click 'Create Database' and select 'Postgres'"
echo ""
echo "3. Name it: bttr-conversations"
echo ""
echo "4. Select your preferred region (us-east-1 recommended)"
echo ""
echo "5. Click 'Create & Continue'"
echo ""
echo "6. Once created, come back here and run:"
echo "   vercel env pull .env.local"
echo ""
echo "7. Then restart your dev server and visit:"
echo "   http://localhost:3001/api/init-database"
echo ""
echo "That's it! Your conversations will be permanently stored! 🎉"
echo ""
echo "Press Enter to open Vercel Dashboard in your browser..."
read

open "https://vercel.com/bttr/bttr-ai/stores"